#include<iostream>
#include<cstdlib>
using namespace std;

int main(){
    cout<<"\t\t\tWElcome to"<<endl;
    cout<<"\t\tGuess the Number Game\n\n";

    cout<<"You have to guess number between 1 to 100.\nComputer will let you know that your guess number is low or high from the random number or you have guessed it right and by how many chances you have guessed it.\n\n";

    int randomNumber, guess, chances = 0;

    //to generate different random numbers every time the game begins.
    srand(time(0));

    //to generate a random number between 1-100
    randomNumber = (rand()%(100-1)+1);

    do{

        cout<<"Enter your guessed number between 1 to 100: ";
        cin>>guess;

        chances++;

        if(guess>randomNumber){
            cout<<"Your guess "<<guess<<" is too high!!!"<<endl;
            cout<<endl;
        }
        else if(guess<randomNumber){
            cout<<"Your guess "<<guess<<" is too low!!!"<<endl;
            cout<<endl;
        }
        else{
            cout<<"Your guess "<<guess<<" has matched with the random number generated by computer\n";
            cout<<"You had taken " <<chances<<" chances to get the right number.";
        }
    }while(guess!=randomNumber);

    return 0;

}